### ISSUE TITLE
How do I set invocation metadata with the reflection generated client?

### ISSUE THREAD

**Issue by barath-atomleap** [kensho-technologies/eagr#11]
This is a great library! Thanks for the effort!

I'm trying to use the client generated by reflection with `make_json_grpc_client`, but I can't seem to find a way to set `context.invocation_metadata`. Could you clarify if this is possible and how I could achieve this?

**Comment by ljades** [comment]
Hey Barath,

Thank you for reporting this. Currently, it is not possible, but I will get an update in soon to add the ability to set that, timeout, and credentials as well.

**Comment by barath-atomleap** [comment]
That's great! Thanks!

**Comment by ljades** [comment]
The latest version with the invocation functionality expanded is now published on PyPi as v0.2.0.
