### ISSUE TITLE
Unpin flask

### ISSUE THREAD

**Issue by lodrion** [kensho-technologies/eagr#17]
Is there a reason why flask is caret-pinned?
I don't recall anything that depends on version being that low and caret-pin stops the march forward:)

**Comment by ljades** [comment]
Thanks for bringing this up! PR is out now, version release bump soon after!
https://github.com/kensho-technologies/eagr/pull/18

**Comment by ljades** [comment]
Latest version published with flask unpinned

**Comment by lodrion** [comment]
Thank you!
