### ISSUE TITLE
GRPC Reflection Usage

### ISSUE THREAD

**Issue by aarnone** [kensho-technologies/eagr#8]
Hi,

I've tried to run the reflection client as described in the [README](https://github.com/kensho-technologies/eagr#grpc-reflection-interface), but it fails with the following error:

```python
Traceback (most recent call last):
  File "eagr_demo.py", line 9, in <module>
    generic_myservice_client = grpc_reflection_interface.make_json_grpc_client(host, service)
TypeError: make_json_grpc_client() missing 1 required positional argument: 'service_name'
```

I see that the method `make_json_grpc_client` has a `self`, but I'm not sure how it's supposed to be bound. Could you please advise?

Thanks!

**Comment by ljades** [comment]
Hi @aarnone, thank you for reporting this. This is a bug--it's a remnant of some migrated code, and one of the only spots with no unit tests yet written.

Here is a draft PR, and I tested it against some of my own services:
https://github.com/kensho-technologies/eagr/pull/9

I plan on writing unit tests before merging, and then I'll release the next version as soon as it is merged. If you'd like to pull the branch and test it yourself to verify in the meantime, you are welcome to do so.

**Comment by aarnone** [comment]
Hi @ljades, thanks for the quick response!

I've tried locally and it works great 👍

**Comment by ljades** [comment]
v0.1.1 has been published with the fix. Thanks again for reporting the issue.
